from abc import ABC, abstractmethod

from llm.llm_types import LLMResponse


class LLM(ABC):
    """ Abstract base class for all LLM implementations. Defines the interface that all LLMs must implement. """
    @abstractmethod
    def generate(self, prompt: str, tools: list[dict] = []) -> LLMResponse:
        """Generate a response from the LLM.

        Args:
            prompt (str): The input prompt to send to the LLM. 
            tools (list[dict], optional): A list of tools that can be used by the LLM. Defaults to [].

        Returns:
            LLMResponse: The response generated by the LLM.
        """
        pass
    
    @abstractmethod
    def batch_generate(self, prompts: list[str], tools: list[list[dict]] = None) -> list[LLMResponse]:
        """Generate multiple responses to different prompts and available tools from the LLM.

        Args:
            prompts (list[str]): A list of input prompts to send to the LLM.
            tools (list[list[dict]], optional): A list of tools that can be used by the LLM for each prompt. Defaults to None.

        Returns:
            list[LLMResponse]: A list of responses generated by the LLM.
        """
        pass