from typing import override
from queue import Queue, Empty

from openai import OpenAI
import time
from concurrent.futures import ThreadPoolExecutor
from tqdm import tqdm

from llm.llm import LLM
from llm.llm_types import LLMConfig, LLMResponse, ToolCall


class OllamaLLM(LLM):
    """ Implementation of the LLM interface for interacting with the Ollama API. 
    It specifically allows to connect to multiple Ollama endpoints to concurrently generate with batch_generate."""

    def __init__(self, configs: list[LLMConfig]):
        """Initialize an OllamaLLM object.

        Args:
            configs (list[LLMConfig]): A list of configuration objects for the Ollama API endpoints.

        Raises:
            ValueError: If the model_name in the provided configs are not the same. 
        """
        self.model_name = configs[0].model_name
        for i in range(1, len(configs)):
            if configs[i].model_name != self.model_name:
                raise ValueError("All configs must have the same model_name.")

        self.clients = [OpenAI(
            api_key=config.api_key,
            base_url=config.base_url,
            timeout=1800
        ) for config in configs]

    @override
    def generate(self, prompt: str, tools: list[dict] = []) -> LLMResponse:
        raise NotImplementedError(
            "If you are not using batch_generate, use the OpenAiLLM class instead.")

    def generate_with_client(self, client: OpenAI, prompt: str, tools: list[dict] = []) -> LLMResponse:
        """Generate an LLM response with a specific client.

        Args:
            client (OpenAI): The Ollama client to use.
            prompt (str): The prompt to send to the LLM.
            tools (list[dict], optional): A list of tools to make available to the LLM. Defaults to [].

        Returns:
            LLMResponse: The response generated by the LLM, which can either be a text response or a tool call.
        """
        start_time = time.time()

        # This is the old API, because some models (like big-pickle) do not support the new one
        response = client.chat.completions.create(
            model=self.model_name,
            messages=[
                {"role": "user", "content": prompt}
            ],
            tools=tools,
            tool_choice="auto"
        )

        elapsed_time = time.time() - start_time
        self.log_response_stats(elapsed_time, response)

        if response.choices[0].finish_reason == "tool_calls":
            return LLMResponse(
                text=None,
                tool_call=ToolCall(
                    name=response.choices[0].message.tool_calls[0].function.name,
                    arguments=response.choices[0].message.tool_calls[0].function.arguments
                )
            )

        return LLMResponse(
            text=response.choices[0].message.content,
            tool_call=None
        )

    @override
    def batch_generate(self, prompts: list[str], tools: list[list[dict]] = None) -> list[LLMResponse]:
        """Generate multiple responses to different prompts and available tools from the LLM. 
           This class uses multiple Ollama endpoints simultaneously to achieve concurrency.

        Args:
            prompts (list[str]): A list of input prompts to send to the LLM.
            tools (list[list[dict]], optional): A list of tools to make available to the LLM for each prompt. Defaults to None.

        Raises:
            ValueError: If the length of the tools list does not match the length of the prompts list.
            ValueError: If no Ollama clients are available.

        Returns:
            list[LLMResponse]: A list of responses generated by the LLM, which can either be text responses or tool calls.
        """
        if tools is None:
            tools = [[] for _ in prompts]
        elif len(tools) != len(prompts):
            raise ValueError(
                "Length of tools list must match length of prompts list.")

        if not prompts:
            return []

        if not self.clients:
            raise ValueError("At least one Ollama client is required.")

        llm_responses = [None] * len(prompts)
        jobs: Queue[tuple[int, str, list[dict]]] = Queue()

        for index, (prompt, tool) in enumerate(zip(prompts, tools)):
            jobs.put((index, prompt, tool))

        def process_jobs(client, progress_bar) -> None:
            while True:
                try:
                    index, prompt, tool = jobs.get_nowait()
                except Empty:
                    return

                try:
                    llm_responses[index] = self.generate_with_client(
                        client, prompt, tool)
                finally:
                    jobs.task_done()
                    progress_bar.update(1)

        print(
            f"Processing {len(prompts)} prompts using {len(self.clients)} clients...")
        print(f"Queue size: {jobs.qsize()}")

        with ThreadPoolExecutor(max_workers=len(self.clients)) as executor:
            with tqdm(total=len(prompts), desc="LLM Responses", unit="responses") as progress_bar:
                futures = [
                    executor.submit(process_jobs, client, progress_bar)
                    for client in self.clients
                ]

                for future in futures:
                    future.result()

        return llm_responses
