from openai import OpenAI
from tqdm import tqdm

from llm.llm import LLM
from llm.llm_types import LLMConfig, LLMResponse, ToolCall


class OpenAILLM(LLM):
    """ Implementation of the LLM interface for interacting with the old completions OpenAI API. """
    def __init__(self, config: LLMConfig):
        self.model_name = config.model_name
        self.client = OpenAI(
            api_key=config.api_key,
            base_url=config.base_url,
            timeout=config.timeout
        )

    def generate(self, prompt: str, tools: list[dict] = []) -> LLMResponse:
        """Generate a response from the LLM.

        Args:
            prompt (str): The input prompt to send to the LLM. 
            tools (list[dict], optional): A list of tools that can be used by the LLM. Defaults to [].

        Returns:
            LLMResponse: The response generated by the LLM.
        """

        # This is the old API, because some models (like big-pickle) do not support the new one
        response = self.client.chat.completions.create(
            model=self.model_name,
            messages=[
                {"role": "user", "content": prompt}
            ],
            tools=tools,
            tool_choice="auto"
        )

        # if the LLM decides to call a tool, we return a ToolCall object
        if response.choices[0].finish_reason == "tool_calls":
            return LLMResponse(
                text=None,
                tool_call=ToolCall(
                    name=response.choices[0].message.tool_calls[0].function.name,
                    arguments=response.choices[0].message.tool_calls[0].function.arguments
                )
            )

        # otherwise, we return the text response
        return LLMResponse(
            text=response.choices[0].message.content,
            tool_call=None
        )
    
    def batch_generate(self, prompts: list[str], tools: list[list[dict]] = None) -> list[LLMResponse]:
        """Generate multiple responses to different prompts and available tools from the LLM.

        Args:
            prompts (list[str]): A list of input prompts to send to the LLM.
            tools (list[list[dict]], optional): A list of tools that can be used by the LLM for each prompt. Defaults to None.

        Returns:
            list[LLMResponse]: A list of responses generated by the LLM.
        """
        if tools is None:
            tools = [[] for _ in prompts]
        elif len(tools) != len(prompts):
            raise ValueError("Length of tools list must match length of prompts list.")

        llm_responses = []
        for prompt, tool in tqdm(zip(prompts, tools), total=len(prompts), desc="LLM Responses", unit="responses"):
            llm_responses.append(self.generate(prompt, tool))

        return llm_responses
        
    