from llm.openai_llm import OpenAILLM
from llm.llm_types import LLMResponse, LLMConfig
from enum import Enum
import json
import hashlib

class ReplayMode(Enum):
    RECORD = "record"
    REPLAY = "replay"

class ReplayLLM(OpenAILLM):
    """ A wrapper around OpenAILLM that allows for recording and replaying LLM responses. 
        In RECORD mode, it generates new responses and saves them to a file. 
        In REPLAY mode, it loads responses from a file and returns them without calling the LLM.
        The responses are stored in a dictionary with the prompts as the key.
        So this class gives the same answer if it has saved a response to the identical prompt before.
    """
    def __init__(self, config: LLMConfig, filepath: str, mode: ReplayMode = ReplayMode.REPLAY):
        super().__init__(config)
        self.prompt_responses = HashDictionary()
        self.mode = mode
        self.filepath = filepath
        if self.mode == ReplayMode.REPLAY:
            self.__load_prompt_responses()

    def generate(self, prompt: str, tools: list[dict] = []) -> LLMResponse:
        """Generate a response from the LLM if in RECORD mode, or replay a saved response if in REPLAY mode.

        Args:
            prompt (str): The input prompt to send to the LLM. 
            tools (list[dict], optional): A list of tools that can be used by the LLM. Defaults to [].

        Returns:
            LLMResponse: The response generated by the LLM or replayed from the saved responses.
        """
        if self.mode == ReplayMode.REPLAY:
            return self.__replay_response(prompt)
        else:
            return self.__generate_new_and_record(prompt, tools)
        
    def batch_generate(self, prompts: list[str], tools: list[list[dict]] = None) -> list[LLMResponse]:
        """Generate multiple responses to different prompts and available tools from the LLM.
        In RECORD mode, it generates new responses.
        In REPLAY mode, it returns saved responses without calling the LLM.

        Args:
            prompts (list[str]): A list of input prompts to send to the LLM.
            tools (list[list[dict]], optional): A list of tools that can be used by the LLM for each prompt. Defaults to None.

        Returns:
            list[LLMResponse]: A list of responses generated by the LLM or replayed from the saved responses.
        """
        if tools is None:
            tools = [[] for _ in prompts]
        elif len(tools) != len(prompts):
            raise ValueError("Length of tools list must match length of prompts list.")
        
        if self.mode == ReplayMode.REPLAY:
            responses = []
            for prompt in prompts:
                responses.append(self.__replay_response(prompt))
            return responses
        else:
            responses = super().batch_generate(prompts, tools)
            for prompt, response in zip(prompts, responses):
                self.prompt_responses[prompt] = response
            self.__save_prompt_responses()
            return responses
        
    def __replay_response(self, prompt: str) -> LLMResponse:
        response = self.prompt_responses[prompt]
        if response is None:
            raise ValueError(f"No response found for prompt: {prompt}")
        return response

    def __generate_new_and_record(self, prompt: str, tools: list[dict] = []) -> LLMResponse:
        response = super().generate(prompt, tools)
        self.prompt_responses[prompt] = response
        self.__save_prompt_responses()
        return response
    
    def __save_prompt_responses(self):
        with open(self.filepath, "w") as f:
            json.dump({prompt: response.to_dict() for prompt, response in self.prompt_responses.items()}, f, indent=4)

    def __load_prompt_responses(self):
        with open(self.filepath, "r") as f:
            self.prompt_responses = HashDictionary({prompt: LLMResponse.from_dict(response_data) for prompt, response_data in json.load(f).items()})


class HashDictionary:
    """ A dictionary that hashes its string keys using SHA-256. """
    def __init__(self, data = {}):
        self.data = data

    def __setitem__(self, key, value):
        hashed_key = self.hash_key(key)
        self.data[hashed_key] = value

    def __getitem__(self, key):
        hashed_key = self.hash_key(key)
        return self.data[hashed_key]

    def __contains__(self, key):
        hashed_key = self.hash_key(key)
        return hashed_key in self.data
    
    def items(self):
        return self.data.items()

    def hash_key(self, key):
        if isinstance(key, str):
            return hashlib.sha256(key.encode()).hexdigest()
        else:
            raise TypeError("Keys must be strings.")